# Generated by Django 5.1.2 on 2024-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("article", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100)),
                ("supplier", models.CharField(max_length=100)),
                ("basic_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_quantity", models.IntegerField()),
                ("review_rating", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
