# Generated by Django 5.1.2 on 2024-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildberries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="basic_price",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
