# Generated by Django 5.1.2 on 2024-10-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildberries", "0002_alter_product_basic_price_alter_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="review_rating",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
